use_frameworks!

target 'ARGKit_Example' do
  pod 'ARGKit', :path => '../'

  target 'ARGKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
